### ISSUE TITLE
Use of CEL decoding in DGEngine

### ISSUE THREAD

**Issue by ghost** [savagesteel/d1-graphics-tool#1]
Hi there,

First of all, this is a really nice tool.

I'm the author of DGEngine (https://github.com/dgengin/DGEngine) and I have written a new implementation for CEL/CL2 decoding based on this project (which is more accurate than the one I was using before) that I would like to integrate with DGEngine. I modified it not to use QT related classes, etc.

I would like to know if it's OK to do so and if I can keep using the ZLib license, since your project uses GPL which is incompatible.

**Update:** I have committed the new CEL decoder code today (22/04/2018). Let me know if you have any objection.

Regards,
DGEngine author

**Comment by savagesteel** [comment]
Hello,

Thanks for asking, of course you can use it without any limitations, I put it on GitHub for the sole purpose of sharing.
If you notice any issue in the algorithms or in my understanding of the PAL/TRN/CEL/CL2 file formats please let me know I would like to update my d1-file-formats repo.

Regards,

Savagesteel

**Comment by ghost** [comment]
Thanks, it's working great. :+1:
