### ISSUE TITLE
View SOL attributes for level tile pices

### ISSUE THREAD

**Issue by AJenbo** [savagesteel/d1-graphics-tool#11]
The .sol format is a simple set of flags that informs the engine what attributes a tile piece has.

Each byte in the file is a bit flag corresponding to the tile of the same number as the byte.
- `0x01` Solid
- `0x02` Blocks light
- `0x04` Blocks missiles
- `0x08` Transparent
- `0x10` Left masked arch
- `0x20` Right masked arch
- `0x40` Unused
- `0x80` Can hold wall object

Note that once this is implemented my next request would be for an option to edit an save .sol, so probably use some checkboxes for displaying this info :sweat_smile:

**Comment by nickgavran** [comment]
I'd absolutely love for this to be implemented. 
I have a lot of custom dPieces that I need to apply some .sol attributes to, but currently I have no way of doing so.
