### ISSUE TITLE
Fix MSVCP140D.dll error.

### ISSUE THREAD

**Issue by imagicalFantasy** [savagesteel/d1-graphics-tool#114]
I can't launch Software on windows. Even if I installed all redistributable packages.

From the web I seen :
The message of missing VCRUNTIME140D.dll is indicative of trying to run a debug binary on a machine that does not have the debug VisualC++ run time binaries installed. The VisualC++ debug run time is installed with Visual Studio. If you wish to run the binary on a different machine, please rebuild the project as Release.

Also, I tried previous build "0.5.0" this version run without problem.

**Comment by StephenCWills** [comment]
The release was indeed built as Debug. It's something we fixed shortly after the release. Try downloading the artifact from the latest GitHub Actions build.

https://github.com/diasurgical/d1-graphics-tool/actions/workflows/windows.yml?query=branch%3Amaster

**Comment by AJenbo** [comment]
Yeah it's fixed and I just need to produce a new release, but there was a couple of things I wanted to test and I found an issue with how the program access it's settings on Linux that I was hoping to fix as well before releasing the next version.
