### ISSUE TITLE
Prebuild Linux binery

### ISSUE THREAD

**Issue by AJenbo** [savagesteel/d1-graphics-tool#13]
Hey @savagesteel the situation with Qt6 on Linux has gotten a lot better. 6.2.4 is available on Ubuntu since 21.10.

As such it's now possible to create a .deb install file that depends on it for a minimal installation size.

Attached is a build of the latest master (no changes), I also added an application short cut for it (using the .svg file as the icon).

[d1-graphics-tool-0.5.0.zip](https://github.com/savagesteel/d1-graphics-tool/files/9284400/d1-graphics-tool-0.5.0.zip)

I tested the package on Ubuntu 22.04 LTS with a clean install in a VM

![image](https://user-images.githubusercontent.com/204594/183496236-d33e7947-153f-4a36-add5-4692eddf2c55.png)

The additional dependencies (fetched form the official Ubuntu repo) is pretty manageable:
```
Need to get 9,516 kB of archives.
After this operation, 33.3 MB of additional disk space will be used.
```
(worst case senario, if no other Qt6 apps are installed)

Hope this is helpful :)

**Comment by AJenbo** [comment]
When installing:
![image](https://user-images.githubusercontent.com/204594/183497380-bd9e0849-6f52-4d8b-83fc-58e8e65afbff.png)

**Comment by savagesteel** [comment]
@AJenbo Thanks for looking into this, I added the deb file to the latest release page.

**Comment by AJenbo** [comment]
Here is a bulky appimage of 26MB for anyone not on a recent Debian derivative:
[Diablo_1_Graphics_Tool-077e9cf-x86_64.zip](https://github.com/savagesteel/d1-graphics-tool/files/9285110/Diablo_1_Graphics_Tool-077e9cf-x86_64.zip)
