### ISSUE TITLE
are you the savagesteel from the dark?

### ISSUE THREAD

**Issue by ghost** [savagesteel/d1-graphics-tool#3]
hey mate didn't you do some work on the dark?

I am trying to figure the palette system in diablo . Looking throught your code  I think you might be able to help.

check it out.

https://github.com/diasurgical/devilution

**Comment by savagesteel** [comment]
Hello,

Sorry for the late reply, I was not involved with the dark development but I did post on the dark modding forums.

I put all I know about Diablo 1 file formats in the following repo:
https://github.com/savagesteel/d1-file-formats

More specifically you can check:
https://github.com/savagesteel/d1-file-formats/blob/master/PAL.md
https://github.com/savagesteel/d1-file-formats/blob/master/TRN.md

I hope it helps.
