### ISSUE TITLE
Reproduce handling of TRNs in Diablo

### ISSUE THREAD

**Issue by pionere** [savagesteel/d1-graphics-tool#36]
In Diablo 1 when a TRN file is loaded, every value of 0xFF is set to zero. In order to reproduce the in-game result, it would be nice to apply this logic here as well.
This is not true for translations of unique monsters -> make it optional?

**Comment by mewmew** [comment]
For reference, from `TranslateMonsterGFX`:
```cpp
if (*pData == 255) {
	*pData = 0;
}
```
where `pData` is the TRN buffer.

**Comment by mewmew** [comment]
>  This is not true for translations of unique monsters -> make it optional?

Is this a bug in the original game? That is, should it also be true for unique monsters??

**Comment by pionere** [comment]
> Is this a bug in the original game? That is, should it also be true for unique monsters??

Most probably it is a bug: 
![Steelmace](https://user-images.githubusercontent.com/7431458/201861342-1fee0a88-074e-4996-b915-2cdac2070a0c.png)
Steelmace
![Sludge](https://user-images.githubusercontent.com/7431458/201861390-c416c00a-b841-460c-a0d5-0d754ec77c5e.png)
Baron Sludge

Even if it is fixed later, @savagesteel / @AJenbo might want to keep it optional because AFAIK the target of this application is the original Diablo.

**Comment by AJenbo** [comment]
DevilutionX actually "fixed" this issue by mistake around 1.2.0. But as a consequence white was missing ...

**Comment by pionere** [comment]
> DevilutionX actually "fixed" this issue by mistake around 1.2.0. But as a consequence white was missing ...

I could not find it in the changelog. What do you mean by missing white?

**Comment by AJenbo** [comment]
it might have been fixed before an actual release happened. the white color was missing from the palette. i think we where only fadin in 255 colors instead of 256 as i remember it

**Comment by pionere** [comment]
hm.. So a proper fix would not cause any issue, right?
