### ISSUE TITLE
Cant start it - Error - This application failed to start brcause no QT platform plugin could be inicialized.

### ISSUE THREAD

**Issue by ruthan** [savagesteel/d1-graphics-tool#4]
Hello,
i cannot start the tool, i getting this error:
This application failed to start brcause no QT platform plugin could be inicialized.

 I tried multiple Win10 machines, Win 7 machien and WinXP 32 bit machine, its nothing working only of them.

 Version 0.0.3 is fine, but it has much more files that version 0.0.3.

 I found newer version here:
https://github.com/Elidevin/Diablo-1-Graphics-Tool

 But it has not possibility to add the issues.. I dunno how exactly are these project connected.

**Comment by savagesteel** [comment]
Hi @ruthan ,

Thanks for trying the tool.
I'm running v0.3.1 without any issue on my Windows 10 x64 machine.
Can you please try the new version I just published: https://github.com/savagesteel/d1-graphics-tool/releases/tag/0.3.2 ?
After you extract it do not move/delete any of the included files and just run `D1GraphicsTool.exe`.
Please let me know if it works this time.

**Comment by savagesteel** [comment]
Hello, I'm closing this issue since it has been opened for more than one year, please feel free to contact me if you are still having issues with the latest version.

**Comment by savagesteel** [comment]
Hello, I'm closing this issue since it has been opened for more than one year, please feel free to contact me if you are still having issues with the latest version.

**Comment by ruthan** [comment]
New version is working.
