### ISSUE TITLE
order of translations (TRN)

### ISSUE THREAD

**Issue by pionere** [savagesteel/d1-graphics-tool#7]
At the moment the handling of multiple translations is unintuitive, because the user has to select the translations in reversed order.
For example in case of "Shadowdrinker" (where the "Monsters\SkelSd\SklSr*.CL2" file is used with "Levels\L2Data\L2_*.pal") the base translation is "Monsters\\SkelSd\\Black.TRN" from the monster-type and the unique translation is "Monsters\Monsters\SHDR.TRN". To recreate the look in the game, the SHDR.TRN has to be set as "Translation 1", while the Black.TRN must be the "Translation 2".

I tried to change the order of D1Trn entities in my branch, but the update order would have to be updated as well. The result would be an unnecessary complicated code so maybe a simpler approach would be preferred.
E.g. re-label the fields to "Base Translation"/"Unique Translation", or change the order on the gui, or add some tooltip, or just leave it as it is. Or maybe you have a better idea?

PS: this is a very useful tool.

**Comment by savagesteel** [comment]
Hello, thanks for reporting this, I'm rewriting the UI around PAL/TRN to include editing support so I will definitely have a look at this.

**Comment by savagesteel** [comment]
I was able to reproduce the issue, this is actually impacting most of the unique monsters.
The odd thing though is that for Snotspill (phalla.cl2) it works the other way around first TRN has to be blue.trn and second one bng.trn.
I have some other odd examples like Red Vex or Black Jade that I cannot get displayed properly.
I will further investigate.

**Comment by pionere** [comment]
> The odd thing though is that for Snotspill (phalla.cl2) it works the other way around first TRN has to be blue.trn and second one bng.trn.

Are you sure about it? In my game (and e.g. http://lesyn.com/image/diablo117.jpg ) Snotspill is just blue. If I select blue.trn first and bng.trn second, it gets yellow spots on its skin.

> I have some other odd examples like Red Vex or Black Jade that I cannot get displayed properly.

Seems to work for me.

**Comment by savagesteel** [comment]
> Are you sure about it? In my game (and e.g. http://lesyn.com/image/diablo117.jpg ) Snotspill is just blue. If I select blue.trn first and bng.trn second, it gets yellow spots on its skin.

You are right on this one my memory is bad.

> Seems to work for me.

I don't think it matches the original, for Red Vex if I open scbsa.cl2 with trn1 as redv.trn and trn2 as succrw.trn the monster looks blue.
If I switch TRNs it's still not the expected outcome I checked a Youtube video of Lazarus' lair.

I'll continue investigating.

**Comment by pionere** [comment]
This is what I get:
![blkjd](https://user-images.githubusercontent.com/7431458/125905826-bed0ec4d-4268-445c-b434-c84c3b414d86.png)
![redv](https://user-images.githubusercontent.com/7431458/125905852-a5c0e305-fb4b-4281-add3-79adf1dea8f6.png)

The translations need to be applied in reversed order, because in game the translations are applied to the monster, then the palette is used for the result, while in the tool the translations are applied to the palette and the result is used on the monster. This is not the same if one translation alters the result of the other translation.

**Comment by savagesteel** [comment]
Your screenshots are not from stock v0.4.1 you made some modifications to the code right?

> The translations need to be applied in reversed order, because in game the translations are applied to the monster, then the palette is used for the result, while in the tool the translations are applied to the palette and the result is used on the monster. This is not the same if one translation alters the result of the other translation.

Ok I understand.

**Comment by pionere** [comment]
I'm using stock v0.4.0 (on a 32-bit system)

**Comment by savagesteel** [comment]
Ok I have an issue when running the tool on my 64-bit OS, here is the result with stock v0.4.0:

<img width="401" alt="2021-07-16 20_38_02-Clipboard" src="https://user-images.githubusercontent.com/36926406/125993933-9dcefced-9699-4f92-92c5-90aad7ee150d.png">

**Comment by savagesteel** [comment]
I tried v0.4.0 both on my 64-bit system and a 32-bit VM, I cannot get the same result.

**Comment by nickgavran** [comment]
This is what I get:
![image](https://user-images.githubusercontent.com/60329165/126006268-92dc21c3-25f6-497f-892a-f9c55d17bb8d.png)

![image](https://user-images.githubusercontent.com/60329165/126006330-16bf39d7-acbf-4564-9683-971cb5699853.png)

As you can see, neither of them look right. In fact, I am not able to reproduce their correct look at all. 
@pionere your trn files have odd names, using capital letters, which is not normal. Are you sure this is not modified somehow, and that you are using the default trns?

**Comment by nickgavran** [comment]
This is what I get with the trns you have chosen: 
![image](https://user-images.githubusercontent.com/60329165/126006979-24ebf6d4-2ed6-4c85-b667-c15c9b058cc8.png)
![image](https://user-images.githubusercontent.com/60329165/126006997-a47869eb-dc15-4e8e-87a1-782fd037e7d7.png)

As you can see, neither of them look right.
I can achieve the correct look of Red vex; 
![image](https://user-images.githubusercontent.com/60329165/126007089-0ba354b3-4ca2-49f5-a292-f198fa65bf87.png)

However I cannot achieve the correct look of Dark Jade with any combination.

@pionere Are you absolutely sure that your files aren't modified in any way? I noticed your trn files have capitalized letters in them, which is not their default naming scheme. EDIT: Ok, apparently the naming scheme is correct, I am using a different listfile from yours.

**Comment by savagesteel** [comment]
@nickgavran Thanks for sharing, I have the exact same outcome.

For reference the checksums of the files:

```
Algorithm       Hash                                                                   Path
---------       ----                                                                   ----
SHA256          0AB4D35F11878A6E5B7CC398D8A5427B9D97009A826A6138C3B838A0F596B2C9       scbsa.cl2
SHA256          D4F90E962BAEEA3DA3DF336DE86EFD1488D8FB92AA2DC977BCB90D523958A158       succrw.trn
SHA256          3FC7E919A0882960AC25A2BDE2F3A381A37294DFC5EDF9CA6D770E13FD759EFB       redv.trn
```

I think the names used by @pionere are exact, they match what is in the game code case-wise.
The names can be lower case when they are lower case in the list file used with the MPQ extraction tool.

**Comment by pionere** [comment]
My checksums of the files (Ladik's MPQ Editor 3.6.0.867):

 ```
 Algorithm       Hash                                                                   Path
 ---------       ----                                                                   ----
 SHA256          0AB4D35F11878A6E5B7CC398D8A5427B9D97009A826A6138C3B838A0F596B2C9       Scbsa.CL2
 SHA256          D4F90E962BAEEA3DA3DF336DE86EFD1488D8FB92AA2DC977BCB90D523958A158       Succrw.TRN
 SHA256          9D95DEE82596DDE148BA25404B6A3C93858C965292870B3ACCE5E5F469D2F9D6       REDV.TRN
 SHA256          40288DB21CB778112D8BCF2CC6C0968E43AFD49CD95977022D928E119D763C2B       BLKJD.TRN
 ```

Which means the translation files do not match.

**Comment by savagesteel** [comment]
Wow! I extracted DIABDAT.MPQ yesterday with MPQ Editor 3.6.0.854 x64 on my Windows 10 x64 machine.
I retried today with 3.6.0.858 both x64 and x86, also tried on a Windows 7 32-bit virtual machine and I still end-up with the following checksum for Red Vex:

```
Algorithm       Hash                                                                   Path
---------       ----                                                                   ----
SHA256          3FC7E919A0882960AC25A2BDE2F3A381A37294DFC5EDF9CA6D770E13FD759EFB       redv.trn
```

**Comment by savagesteel** [comment]
For reference:
There are two versions of both `REDV.TRN` and `BLKJD.TRN` files in `DIABDAT.MPQ`.
One in the `Monsters\Succ` folder and one in the `Monsters\Monsters` folder.
The correct files are `Monsters\Monsters\REDV.TRN` and `Monsters\Monsters\BLKJD.TRN`.
