### ISSUE TITLE
Feature Request: open level CEL via MIN file

### ISSUE THREAD

**Issue by pionere** [savagesteel/d1-graphics-tool#8]
Currently the only way to open a level-CEL file is to select an existing CEL file and let the program guess its type.
This works for the existing level-CEL files, but prevents the user from experimenting with new assets, because D1Cel::load expects at least 512 matching (trapezoid, triangle or square) entries before D1CEL_TYPE::V1_LEVEL is set.
Since this approach is quite ad hoc (the new assets might have no such entries at all) and requires a huge amount of assets up-front, it would be nice to have an option to open MIN files directly.

**Comment by mewmew** [comment]
Related to #2.

**Comment by pionere** [comment]
another not modder friendly way is how the MIN-type is [calculated](https://github.com/savagesteel/d1-graphics-tool/blob/305a5526c419177ae6dc5678e06d7d3c71951555/source/d1min.cpp#L61). Maybe doing it based on the file-size would be better?

The best would be an input field to set manually.

**Comment by AJenbo** [comment]
@pionere would you be willing to work on some of this? Then I can probably review and add it for the next release.

**Comment by pionere** [comment]
> @pionere would you be willing to work on some of this? Then I can probably review and add it for the next release.

well, the latest version is not compatible with my system (win32), so...

**Comment by AJenbo** [comment]
Oh... what changed?

**Comment by AJenbo** [comment]
Level CELs are now detected by the pressens of the accompanying .sol, .min and a .til.
https://github.com/savagesteel/d1-graphics-tool/commit/a515972114d35e467a2b71d92df8e6ca9e8992e7

This also removes the restriction of sub-tiles being either 5 (160px) or 8 (256) frames tall. This does mean that all 4 files must be valid for thing to load correctly, but much less guess work is being applied so there should be less (no?) incorrect results.
